name: Video Botu
on:
  schedule:
    - cron: '0 0 * * *' # Her 24 saatte bir çalışır
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sistem Kurulumu
        run: |
          sudo apt-get update
          sudo apt-get install imagemagick -y
          pip install --upgrade pip
          pip install moviepy==1.0.3 google-api-python-client google-auth-oauthlib
      - name: Botu Tetikle
        run: python ana_bot.py
      - name: Sirayi Guncelle
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add siradaki_soz.txt
          git commit -m "Sira guncellendi" || echo "Degisiklik yok"
          git push
