name: Video Botu
on:
  schedule:
    - cron: '0 17,19 * * *' # Türkiye saatiyle 20:00 ve 22:00 (UTC 17:00 ve 19:00)
  workflow_dispatch: # Canın sıkıldığında elle basman için buton duruyor

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3

      - name: Sistem Kurulumu
        run: |
          sudo apt-get update
          sudo apt-get install imagemagick -y
          # ImageMagick güvenlik kilidini açıyoruz
          sudo sed -i 's/domain="path" rights="none" pattern="@\*"/domain="path" rights="read|write" pattern="@\*"/g' /etc/ImageMagick-6/policy.xml
          pip install moviepy==1.0.3 google-api-python-client google-auth-oauthlib

      - name: Botu Tetikle
        run: python ana_bot.py

      - name: Sirayi Guncelle ve Kaydet
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add siradaki_soz.txt
          git commit -m "Sira guncellendi" || echo "Degisiklik yok"
          git push
