name: Video Botu
on:
  schedule:
    - cron: '0 9 * * *' # Türkiye saatiyle her gün tam 12:00'de çalışır
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sistem Kurulumu ve Guvenlik Kilidini Ac
        run: |
          sudo apt-get update
          sudo apt-get install imagemagick -y
          # BURASI KRİTİK: Güvenlik engelini kaldırıyoruz
          sudo sed -i 's/domain="path" rights="none" pattern="@\*"/domain="path" rights="read|write" pattern="@\*"/g' /etc/ImageMagick-6/policy.xml
          pip install --upgrade pip
          pip install moviepy==1.0.3 google-api-python-client google-auth-oauthlib
      - name: Botu Tetikle
        run: python ana_bot.py
      - name: Sirayi Guncelle
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add siradaki_soz.txt
          git commit -m "Sira guncellendi" || echo "Degisiklik yok"
          git push
